### OpenPsychometrics
## Taylor Manifest Anxiety Scale: http://openpsychometrics.org/_rawdata/TMA.zip

data_url_location = "http://openpsychometrics.org/_rawdata/WPI.zip"
data_local_location = "data-raw/woodworth-psychoneurotic-inventory/WPI.zip"

# Download the zip file
download.file(data_url_location,
              data_local_location)

# Unzip and load anxiety data into R
# Note, data has a header in it!
raw_wpi =
  readr::read_delim(unz(data_local_location, "WPI/data.csv"),
                    delim = "\t", na = c("", "NA", "-1"),
                    col_types = cols(
                      Q1 = readr::col_integer(),
                      Q2 = readr::col_integer(),
                      Q3 = readr::col_integer(),
                      Q4 = readr::col_integer(),
                      Q5 = readr::col_integer(),
                      Q6 = readr::col_integer(),
                      Q7 = readr::col_integer(),
                      Q8 = readr::col_integer(),
                      Q9 = readr::col_integer(),
                      Q10 = readr::col_integer(),
                      Q11 = readr::col_integer(),
                      Q12 = readr::col_integer(),
                      Q13 = readr::col_integer(),
                      Q14 = readr::col_integer(),
                      Q15 = readr::col_integer(),
                      Q16 = readr::col_integer(),
                      Q17 = readr::col_integer(),
                      Q18 = readr::col_integer(),
                      Q19 = readr::col_integer(),
                      Q20 = readr::col_integer(),
                      Q21 = readr::col_integer(),
                      Q22 = readr::col_integer(),
                      Q23 = readr::col_integer(),
                      Q24 = readr::col_integer(),
                      Q25 = readr::col_integer(),
                      Q26 = readr::col_integer(),
                      Q27 = readr::col_integer(),
                      Q28 = readr::col_integer(),
                      Q29 = readr::col_integer(),
                      Q30 = readr::col_integer(),
                      Q31 = readr::col_integer(),
                      Q32 = readr::col_integer(),
                      Q33 = readr::col_integer(),
                      Q34 = readr::col_integer(),
                      Q35 = readr::col_integer(),
                      Q36 = readr::col_integer(),
                      Q37 = readr::col_integer(),
                      Q38 = readr::col_integer(),
                      Q39 = readr::col_integer(),
                      Q40 = readr::col_integer(),
                      Q41 = readr::col_integer(),
                      Q42 = readr::col_integer(),
                      Q43 = readr::col_integer(),
                      Q44 = readr::col_integer(),
                      Q45 = readr::col_integer(),
                      Q46 = readr::col_integer(),
                      Q47 = readr::col_integer(),
                      Q48 = readr::col_integer(),
                      Q49 = readr::col_integer(),
                      Q50 = readr::col_integer(),
                      Q51 = readr::col_integer(),
                      Q52 = readr::col_integer(),
                      Q53 = readr::col_integer(),
                      Q54 = readr::col_integer(),
                      Q55 = readr::col_integer(),
                      Q56 = readr::col_integer(),
                      Q57 = readr::col_integer(),
                      Q58 = readr::col_integer(),
                      Q59 = readr::col_integer(),
                      Q60 = readr::col_integer(),
                      Q61 = readr::col_integer(),
                      Q62 = readr::col_integer(),
                      Q63 = readr::col_integer(),
                      Q64 = readr::col_integer(),
                      Q65 = readr::col_integer(),
                      Q66 = readr::col_integer(),
                      Q67 = readr::col_integer(),
                      Q68 = readr::col_integer(),
                      Q69 = readr::col_integer(),
                      Q70 = readr::col_integer(),
                      Q71 = readr::col_integer(),
                      Q72 = readr::col_integer(),
                      Q73 = readr::col_integer(),
                      Q74 = readr::col_integer(),
                      Q75 = readr::col_integer(),
                      Q76 = readr::col_integer(),
                      Q77 = readr::col_integer(),
                      Q78 = readr::col_integer(),
                      Q79 = readr::col_integer(),
                      Q80 = readr::col_integer(),
                      Q81 = readr::col_integer(),
                      Q82 = readr::col_integer(),
                      Q83 = readr::col_integer(),
                      Q84 = readr::col_integer(),
                      Q85 = readr::col_integer(),
                      Q86 = readr::col_integer(),
                      Q87 = readr::col_integer(),
                      Q88 = readr::col_integer(),
                      Q89 = readr::col_integer(),
                      Q90 = readr::col_integer(),
                      Q91 = readr::col_integer(),
                      Q92 = readr::col_integer(),
                      Q93 = readr::col_integer(),
                      Q94 = readr::col_integer(),
                      Q95 = readr::col_integer(),
                      Q96 = readr::col_integer(),
                      Q97 = readr::col_integer(),
                      Q98 = readr::col_integer(),
                      Q99 = readr::col_integer(),
                      Q100 = readr::col_integer(),
                      Q101 = readr::col_integer(),
                      Q102 = readr::col_integer(),
                      Q103 = readr::col_integer(),
                      Q104 = readr::col_integer(),
                      Q105 = readr::col_integer(),
                      Q106 = readr::col_integer(),
                      Q107 = readr::col_integer(),
                      Q108 = readr::col_integer(),
                      Q109 = readr::col_integer(),
                      Q110 = readr::col_integer(),
                      Q111 = readr::col_integer(),
                      Q112 = readr::col_integer(),
                      Q113 = readr::col_integer(),
                      Q114 = readr::col_integer(),
                      Q115 = readr::col_integer(),
                      Q116 = readr::col_integer(),
                      age = readr::col_integer(),
                      gender = readr::col_integer(),
                      country = readr::col_character()
                    )
                  )

# Write the items matrix
#usethis::use_data(woodworth, overwrite = TRUE)

# Remove the zip + csv after read in.
file.remove(data_local_location)

